# Generated by Django 3.1.1 on 2020-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_customer_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
