# Generated by Django 3.1.1 on 2020-09-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200905_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='note',
            new_name='Message',
        ),
    ]
