# Generated by Django 3.1.1 on 2020-09-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200906_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='note',
        ),
    ]
