# Generated by Django 3.1.1 on 2020-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200906_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='note',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
