# Generated by Django 3.1.1 on 2020-09-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200907_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frist_name',
            new_name='name',
        ),
    ]
