# Generated by Django 3.1.1 on 2020-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200907_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askqua',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='askqua',
            name='qua',
        ),
        migrations.AddField(
            model_name='askqua',
            name='Answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='askqua',
            name='Question',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='askqua',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='askqua',
            name='status',
            field=models.CharField(choices=[('Seva', 'Seva'), ('Spiritual', 'Spiritual'), ('Other type', 'Other type')], max_length=200, null=True),
        ),
    ]
